name: ReRankerBERT
type: Retriever

encoder:
  _target_: source.encoder.RetrieverBertEncoder.RetrieverBertEncoder
  architecture: bert-base-uncased
  output_attentions: False
  pooling:
    _target_: source.pooling.NoPooling.NoPooling

hidden_size: 768

tokenizer:
  architecture: ${model.encoder.architecture}

lr: 1e-4
base_lr: 1e-6
max_lr: 1e-4
weight_decay: 1e-2

loss:
  _target_: source.loss.NTXentLoss.NTXentLoss
  params:
    name: NTXentLoss
    miner:
      relevance_map:
        dir: ${data.dir}
    criterion:
      temperature: 0.07
      mat_based_loss: True

metric:
  relevance_map:
    dir: ${data.dir}
  num_nearest_neighbors: 10
  index: ${eval.index}